name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Adjust the Ruby version as needed
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Database for Supabase
        env:
          RAILS_ENV: test
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}  # Make sure to set your secret in GitHub Secrets
        run: |
          PGPASSWORD=$SUPABASE_PASSWORD psql -h $SUPABASE_HOST -U $SUPABASE_USER -d $SUPABASE_DB -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'account_api_test';"
          
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}  # Use the same Supabase database URL for tests
        run: bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
